#default: 
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: topcomp_development
  username: ubuntu
  password: ubuntu
  host: localhost
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000
production:
  adapter: postgresql
  encoding: unicode
  database: topcomp_production
  username: ubuntu
  password: ubuntu
  host: localhost
test: 
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
